### ISSUE TITLE
Java Support?

### ISSUE THREAD

**Issue by Dhruvkanani** [Chrisvin/FlipTabs#1]
I want to use this library in java

**Comment by Chrisvin** [comment]
`FlipTabs` was written in Kotlin which should allow for [Java interop](https://kotlinlang.org/docs/reference/java-interop.html).
Are there any use cases that break when you use it in a Java class?

**Comment by Dhruvkanani** [comment]
It doesn't matter whether it is used in kotlin or java, it has color
problem. When I am using overall color or highlight color attribute it
fills color only in half of the flip tab and also it only happens until you
click on the tab for the first time.
After it is clicked once it becomes perfect.
In short it has overall color and highlight color attribute problem.
Please solve this problem asap because i want to use this in my project.

**Comment by Dhruvkanani** [comment]
It doesn't matter whether it is used in kotlin or java, it has color problem. When I am using overall color or highlight color attribute it fills color only in half of the flip tab and also it only happens until you click on the tab for the first time.
After it is clicked once it becomes perfect.
In short it has overall color and highlight color attribute problem.

**Comment by Chrisvin** [comment]
I was unable to reproduce the issue you've mentioned.
Can you share the code you've used and a screenshot showing the issue?

**Comment by Dhruvkanani** [comment]
//I am using FlipTab in a fragment

FlipTab.xml

<com.jem.fliptabs.FlipTab
android:layout_width="180dp"
android:id="@+id/s1_global"
android:layout_height="70dp"
android:textStyle="bold"
app:wobbleAngle="3"
android:layout_marginEnd="-10dp"
app:wobbleReturnAnimationDuration="200"
app:flipAnimationDuration="500"
app:leftTabText="OFF"
app:rightTabText="ON"
android:layout_marginTop="-10dp"
android:layout_marginBottom="-20dp"
android:layout_alignParentEnd="true"
app:layout_constraintBottom_toBottomOf="parent"
app:layout_constraintEnd_toEndOf="parent"
app:layout_constraintStart_toStartOf="parent"
app:layout_constraintTop_toTopOf="parent"
app:startingTab="left" />

FlipTab.java

FlipTab s1_global = getActivity().findViewById(R.id.s1_global);
s1_global.setOverallColor(getResources().getColor(R.color.colorHackSwitch));

ScreenShot of Output is below:

![ss](https://user-images.githubusercontent.com/42505842/82182330-bfcb2500-9901-11ea-83ee-65c9bf6ebd0d.png)

**Comment by Chrisvin** [comment]
Thanks for bringing this to my attention. This has been fixed in release `v1.1`.
