### ISSUE TITLE
Doesn't supports RTL and setenabled attribute

### ISSUE THREAD

**Issue by Dhruvkanani** [Chrisvin/FlipTabs#4]
I tried rtl but it doesn't shows well. I also want to disable the fliptab for sometime but when i tried fliptab.setenabled(false) it doesn't worked. I can still interact with the fliptab. Waiting for your reply and a solution. Thank You.

**Comment by Dhruvkanani** [comment]
If RTL can't be solved its ok but I need to use setEnabled attribute to enable or disable a fliptab. Thank You.

**Comment by Chrisvin** [comment]
`setEnabled` has been fixed in version `v1.4`
The overall disabled state color can be changed using `setDisabledColor`, or the specific colors by passing a ColorStateList in `setTextColor` / `setHighlightColor`

**Comment by Chrisvin** [comment]
I'm not too familiar with RTL cases, but in `FlipTabs` case it shouldn't break since the text is always centered.
Can you share a screenshot of an RTL case that breaks for you?

**Comment by Dhruvkanani** [comment]
![IMG_20200915_163419](https://user-images.githubusercontent.com/42505842/93204436-b8167280-f773-11ea-92a3-589f73d13ada.jpg)

**Comment by Chrisvin** [comment]
RTL support has been added in version `v1.5`
