### ISSUE TITLE
Cannot set text size lower than 12sp and specify text margin

### ISSUE THREAD

**Issue by Queike** [Chrisvin/FlipTabs#5]
I know that this is not a bug, but I need for my project really small flip tab with small text and small text margin like 2dp (you set text marginTop and marginBottom to 8dp). Can you please provide a posibility to set flip tab attributes really small?

**Comment by Chrisvin** [comment]
The `TextView`s in FlipTab can be acccessed using `getTextViews()` fn, which can then be used to assign the attributes you require.
Something along the following lines should work,
```
fliptab.getTextViews().map {
    it.setTextSize(TypedValue.COMPLEX_UNIT_SP, textSize)
    it.setPadding(leftPadding, topPadding, rightPadding, bottomPadding)
}
```

**Comment by Queike** [comment]
Thank you very much for your answer. It works for paddings, but still I can not set text size lower than 8sp.  I think it is because of attribute `app:autoSizeMinTextSize="8sp"`  in `tab_right` and `tab_left`. In sample code that you wrote above I've added also something like 

```
TextViewCompat.setAutoSizeTextTypeUniformWithConfiguration(textView, 1, 17, 1, TypedValue.COMPLEX_UNIT_SP)
```
but it doesn't change anything. Do you have any advice for setting text size lower than 8sp?

**Comment by Chrisvin** [comment]
You could try disabling the auto-size handling before setting the text size.
```
fliptab.getTextViews().map {
    it.setAutoSizeTextTypeWithDefaults(TextView.AUTO_SIZE_TEXT_TYPE_NONE)
    it.setTextSize(TypedValue.COMPLEX_UNIT_SP, textSize)
    it.setPadding(leftPadding, topPadding, rightPadding, bottomPadding)
}
```

**Comment by Queike** [comment]
It requires API lvl 26, but works fine. Thank you very much!
